[package]
name = "grpc_jh"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
futures-util = "0.3.31"
log = "0.4.27"
pretty_env_logger = "0.5.0"
tokio = {version = "1.46.0", features = ["full"]}
yellowstone-grpc-client = "6.1.0"
yellowstone-grpc-proto = "6.1.0"
